spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
      #服务注册中心
        server-addr: peer1:8848
server:
  port: 8060
management:
  #健康检查
  endpoints:
    web:
      exposure:
        include: "*"
